name: myrss-refactored
version: '3.8'

services:
  myrss:
    image: myrss-refactored:latest
    container_name: myrss-refactored
    restart: unless-stopped
    network_mode: "host"
    volumes:
      # 将主机上的 data 目录挂载到容器的 /app/data，用于持久化数据库 myrss.db 以及配置文件 config.yaml
      - ./data:/app/data
    environment:
      - PORT=8888
      - TZ=Asia/Shanghai
